### ISSUE TITLE
undefined reference to SPR_setDepthSorting

### ISSUE THREAD

**Issue by werton** [Stephane-D/SGDK#106]
I can not compile the starfield_donuts example, the compilation is interrupted
on line 87:
`SPR_setDepthSorting(spr, TRUE);`
with an error:
`main.c|87|undefined reference to SPR_setDepthSorting`
Without this line the example works, although not correctly, but i could not even find SPR_setDepthSorting method in the help, it seems that it does not exist.

**Comment by Stephane-D** [comment]
Oh indeed i forgot to update this sample, removing the line is enough to make it work though.
Why are you thinking the example is not working correctly ?

**Comment by werton** [comment]
I thought that these artifacts were due to the disabling of z sorting. Tried on three different emulators. Is this the way it should be?
![rom_001](https://user-images.githubusercontent.com/4254247/35225470-50b643ec-ff80-11e7-94bf-c2ad4683855d.png)
![rom_000](https://user-images.githubusercontent.com/4254247/35225241-a9d93c78-ff7f-11e7-93dc-7294d8881987.png)

**Comment by Stephane-D** [comment]
Those artifacts are because of the sprite limit per scanline, i should tweak the donuts arrangement to avoid it ;)
Thanks for your report, i fixed the source file to remove the deprecated code :)

**Comment by werton** [comment]
Oh, yes indeed, i did not think about it, thank you :)
Stephane-D, excuse me for offtop, i know that this is not the place for this, i just do not know where else to turn. i will delete this, as you will answer (or do not answer), but could you help me please? I want to register on Spritesmind's forum, but there is disabled registration due to spam. I'm sent email to administrator, but he does not respond. Could you to write to him that there are who wish to register?
ps: sorry for my english:(

**Comment by Stephane-D** [comment]
Ok, but there is luck he don't see my message as well :-/ Can you tell me which nickname / email you used on the forum to subscribe ?

**Comment by werton** [comment]
Many thanks. Usually i sign up under the nickname: werton with email: weerbox@gmail.com. I wrote to the administrator from the same mail.

**Comment by Stephane-D** [comment]
ok, i just sent him a message about it =)

**Comment by werton** [comment]
Thank you very much! :) Can I delete these messages that are not related to SGDK?

**Comment by Stephane-D** [comment]
i'll do it ;)
