### ISSUE TITLE
Makefile Assembly output

### ISSUE THREAD

**Issue by dwc3993** [Stephane-D/SGDK#107]
I'm a big fan of the library's functionality but would love to generate assembly files from the makefile without having to experiment with it extensively. How can I generate assembly files using the makefile and then be able to assemble those with bin/as.exe (flags I would need)? Thanks!

**Comment by minerscale** [comment]
I'm interested in this as well actually, It would be a pretty cool change!

**Comment by Stephane-D** [comment]
I will try to add a special target in makefile as 'assembly' to generate only assembly sources.

**Comment by minerscale** [comment]
Thanks a lot!

**Comment by Stephane-D** [comment]
Added 'asm' target to makefile to generate .lst file contained assembly listing :)

**Comment by minerscale** [comment]
:D
