### ISSUE TITLE
Error : tile [0,0] reference different palette.make: *** [gfx.s] Error 1

### ISSUE THREAD

**Issue by loboere** [Stephane-D/SGDK#112]
when I edit and save the sample image of the sonic background with photoshop
I see this error

--> executing plugin IMAGE...
Error: tile [0,0] reference different palette.make: *** [gfx.s] Error 1
rm gfx.s

the image is indexed and is the same size as the original

**Comment by Stephane-D** [comment]
Not a problem from rescomp but from your image : a tile (8x8 pixels block) cannot address different palette, it looks like it's the case here. You should use a image software which allow to manipulate the palette (as GIMP for instance) to fix that issue
