### ISSUE TITLE
how to see the equivalent of some functions that I believe in my source code in 68k?

### ISSUE THREAD

**Issue by loboere** [Stephane-D/SGDK#113]
example  

```
u16 sum(u16 n)
{
return n+n
}
```

how to see this function in 68k?
can I export in an 68k_asm.txt?
Can I export all the source code in 68k_ams.txt?

**Comment by Stephane-D** [comment]
Just use the 'asm' target of makefile to produce assembly listing : 
`make -f makefile.gen asm`

You should find .lst files in your /out folder of your project containing generated assembly code :)

**Comment by loboere** [comment]
I get this error
`make: *** No rule to make target `asm'.  Stop.`

**Comment by Stephane-D** [comment]
Oh yeah, the new makefile is not yet in the SGDK archive, you should grab it from the repository :  
https://github.com/Stephane-D/SGDK/blob/master/makefile.gen

sorry for the trouble.
