### ISSUE TITLE
Add VRAM defragmentation for the Sprite Engine

### ISSUE THREAD

**Issue by Stephane-D** [Stephane-D/SGDK#115]
When we use the sprite engine, allocating / releasing sprite can end up having the VRAM fragmented, it could be nice to add an option to try to compact (defragment) VRAM allocated blocks when a new VRAM allocation fail (also having a method to do it manually). Basically this method should be part of vram and sprite engine unit.

**Comment by matteusbeus** [comment]
Excellent to see this here :)

**Comment by minerscale** [comment]
Looks good, I like this!

**Comment by Stephane-D** [comment]
done (in wip only, not yet pushed)
