### ISSUE TITLE
XGM stop/start issue

### ISSUE THREAD

**Issue by matteusbeus** [Stephane-D/SGDK#117]
If you put a VDP_waitVSync straight after a XGM_stopPlay you crash the XGM driver.  XGM_startPlay refuses to restart.

```
void playMusic(const u8 *song) {
    stopMusic();
    XGM_startPlay(song);
}

void stopMusic() {
    XGM_stopPlay();
    VDP_waitVSync();
}
```

**Comment by matteusbeus** [comment]
Any news on this? I'm getting close to a full release and it would be nice to know a work around :)

**Comment by Stephane-D** [comment]
In fact the XGM stop / start are quite timing sensitive, can you use XGM_pausePlay() / XGM_startplay() command instead ? In general that is enough to fix the problem :)

**Comment by matteusbeus** [comment]
Thanks! I'll give it a go and see what happens :D

**Comment by Stephane-D** [comment]
Also sometime for stop command, just using 2 VDP_waitVSync instead of 1 is enough to fix the timing issue (because Z80 interpret 68k commands once per frame, but timing isn't exactly a frame, it can be a bit less or more so it's better to wait 2 frames between each command)

**Comment by matteusbeus** [comment]
When you say 2 vsync you mean 1 before and 1 after the stop?

**Comment by Stephane-D** [comment]
Better to put 2 after to let time for the command to be executed.

**Comment by matteusbeus** [comment]
Unfortunately it results in complete silence and the driver won't restart.

**Comment by Stephane-D** [comment]
That is really weird, did you try to use pause instead of stop command ?

**Comment by matteusbeus** [comment]
No I'll try that a little later and post back here.

**Comment by Stephane-D** [comment]
ok :)

**Comment by moon-watcher** [comment]
What I coded for AbbayeMD https://github.com/moon-watcher/AbbayeMD/blob/master/game/src/music.c

**Comment by Stephane-D** [comment]
Oh so you needed 3 waitVSync, that seems a lot..

**Comment by Stephane-D** [comment]
XGM driver got some small fixes lately (take the last sources from repository). The different issues with stop/start commands not always properly working should be fixed. I also recommend to not use XGM_stop() command but XGM_pausePlay() instead as XGM_stop() may need 2 or 3 frames to apply when XGM_pause should take a bit more than 1 frame at worst. Also thanks to Matt from BigEvilCorp who pointed a bug which could let a small remaining sound even after the pause command (DAC write wasn't properly restored) so now you can use it safely.
