### ISSUE TITLE
Visual Studio Support

### ISSUE THREAD

**Issue by thegouldfish** [Stephane-D/SGDK#121]
Hi,

I've written a Visual Studio template for SGDK, which can be found here:
https://www.dropbox.com/s/ty6cwd9y9pib7jk/SGDK.zip?dl=0

just put the zip file in:
%USERPROFILE%\Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C++ Project

It uses a powershell script to setup the environment call make and then process the error log so it shows up in visual studio's error window.

**Comment by Stephane-D** [comment]
Thanks ! I just committed your template in vstudio/template folder so you can directly update / request pull request over it if needed =)
