### ISSUE TITLE
Potential bug with SPR_setVisibility and AUTO_SLOW

### ISSUE THREAD

**Issue by matteusbeus** [Stephane-D/SGDK#123]
If a sprite is added in an X/Y position that results in a section of the sprite being off screen and it's visibility is then set to "AUTO_SLOW".  The off screen section of the sprite will never be visible regardless of its X/Y position.

Sprite dimensions: 192 x 32

`
spr[SPRITE_CLOUD_1] = SPR_addSprite(&cloud_sprite, 16, 200, TILE_ATTR(PAL2, TRUE, FALSE, FALSE));
SPR_setVisibility(spr[SPRITE_CLOUD_1], AUTO_SLOW);
`

**Comment by Stephane-D** [comment]
Fixed :)
