### ISSUE TITLE
fix32Mul overflow?

### ISSUE THREAD

**Issue by timotei** [Stephane-D/SGDK#125]
Hello,

I just did the following sample test which seems it overflows? I am trying to do some calculations that involve doing the squared of a floating-point number:

```
 fix32 x = intToFix32(200);
 fix32 xsquared = fix32Mul(x, x);
 KLog_F2("x: ", x, ", squared: ", xsquared);
```

This prints:

`Message : x: 200.00, squared: -960.00`

I tried with some other numbers and I got good & bad results
```
Message : x: 50.00, squared: -1596.00
Message : x: 46.00, squared: -1980.00
Message : x: 45.00, squared: 2025.00
Message : x: 40.00, squared: 1600.00
Message : x: 30.00, squared: 900.00
```

Am I missing something?

**Comment by Stephane-D** [comment]
That's indeed a overflow issue.
There is several strategy to adopt when doing fixed point multiplication or division, unfortunately each strategy has its drawbacks... here we loss accuracy with high value numbers. I can change the strategy but then we will loss accuracy on small number. Still i may change for something intermediate (but operation will be slower then).
What you can do is to "pre shift" your values first:

>  fix32 x = intToFix32(200);
>  x >>= 5;
>  fix32 xsquared = fix32Mul(x, x) << 10;

**Comment by Stephane-D** [comment]
Can't be fixed (except by using very slow 64 bit multiplication / division but not what we want here)
