### ISSUE TITLE
Sprite Errors and issues!

### ISSUE THREAD

**Issue by Cyndanera** [Stephane-D/SGDK#132]
Okay now I get error please help?

https://pastebin.com/zLBmQVMN

![rom_000](https://user-images.githubusercontent.com/25001333/46906037-9abf3680-cec2-11e8-9ed8-2befb3a3efe2.png)

**Comment by moon-watcher** [comment]
Move that white color to the first position in the palette then clear & compile

**Comment by Stephane-D** [comment]
This is not a bug, if you need support it's better to post in the spritesmind forum :
http://gendev.spritesmind.net/forum/

Thanks :)
