### ISSUE TITLE
Enabling mouse support resulting in CRAM dot crawl.

### ISSUE THREAD

**Issue by thegouldfish** [Stephane-D/SGDK#134]
It seems when you enable mouse support you will get dot crawl anytime you change the palette.
This includes doing fadein / out or just calling VDP_setPalette

it was enabled via: 
JOY_setSupport(PORT_2, JOY_SUPPORT_MOUSE | JOY_SUPPORT_3BTN);

This is on the latest public release 134.

**Comment by Stephane-D** [comment]
Can you provide a very basic code sample reproducing the issue as i can't reproduce it here.
VDP_setPalette(..) shoud be called during VBlank to avoid CRAM dot, using the auto fade methods should work as soon you don't overload DMA.

**Comment by Stephane-D** [comment]
ok, it was due to a very long mouse pooling method. Should be fixed now
