### ISSUE TITLE
Missing { and failed to open "libres.h"

### ISSUE THREAD

**Issue by VreodiumLaurence** [Stephane-D/SGDK#141]
So I wrote a basic code
```
#include <genesis.h>

int main()
{
	while (1)
	{
		VDP_drawText("Hello World! Greetings in Sega Genesis!", 10, 13);
		VDP_waitVSync();
	}

	return(0);
}
```

All is fine and dandy but then I got these errors:
font.h - cannot open source file "libres.h" Line 18
string.h - expected a '{' Line 286
What is going on, what is missing?

**Comment by Stephane-D** [comment]
Check that your SGDK installation is correct, also for the libres.h, you have it in the "release" packages.
But you can also regenerate it by re-building the library :)

**Comment by amaurysilva** [comment]
I have the same problem.
I downloaded the last GDK but the problem continues.
Please help me!! :-(

**Comment by trialforce** [comment]
My project were working fine, then the same error starts from nothing.
