### ISSUE TITLE
rescomp does not give any console output

### ISSUE THREAD

**Issue by igdegoo** [Stephane-D/SGDK#143]
it can be a big problem when resources.h does not generate, it doesnt say anything why

**Comment by Stephane-D** [comment]
It should give console output, weird that it's not your case !
Have you an reproducible example ?

**Comment by igdegoo** [comment]
well im just using the rescomp.jar from 1.40 . it doesnt make any console output wherever i run it under any circumstances

**Comment by Stephane-D** [comment]
Quick test :
![image](https://user-images.githubusercontent.com/619064/61797961-c2b3d100-ae28-11e9-9e02-6f701cff0d63.png)

**Comment by igdegoo** [comment]
oh i think the problem was me typing rescomp.jar into the console i tried java -jar rescomp.jar and it works fine ty
