### ISSUE TITLE
 first SND_startPlay_4PCM() is freezing program

### ISSUE THREAD

**Issue by werton** [Stephane-D/SGDK#150]
The first playing sound by SND_startPlay_4PCM() function,  freezes for some milliseconds the program flow. What is noteworthy is that only the first sound playback slows down the program, further playbacks is not affected on program flow. This can be easily reproducesed using the Sprite example from SGDK distribution, replacing the XGM sound playing with 4PCM.

**Comment by andwn** [comment]
It's loading the 4PCM driver the first time you play a sound. To avoid the delay try to load the driver beforehand with `Z80_loadDriver(Z80_DRIVER_4PCM)`

**Comment by werton** [comment]
It worked, thank you :)
