### ISSUE TITLE
Z80 TFM driver need 32K aligned data which eat many rom space when having many small TFM files !

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Stephane-D/SGDK#16]
```
Change the TFM Z80 driver to avoid that constraint.
```

Original issue reported on code.google.com by `Stephane.D` on 11 Oct 2013 at 1:03

**Comment by Stephane-D** [comment]
TFM driver is now outdated.
A better solution is to export the TFM in VGM format and play it with XGM driver.
