### ISSUE TITLE
Big value

### ISSUE THREAD

**Issue by smalcom** [Stephane-D/SGDK#160]
https://github.com/Stephane-D/SGDK/blob/6255c53b9efa1f3dad4d9f230ef7fdb3836dc285/src/vdp_bg.c#L158

Must be "while(len--)"?

**Comment by smalcom** [comment]
I mean insert
> i = len;
before "while" for not changing "len" which used in VDP_setTileMapDataRectEx.

**Comment by Stephane-D** [comment]
Definitely :p
Thanks for reporting, will be fixed very soon !
