### ISSUE TITLE
XGM Driver Bug (com_pcm_p1_ch1 -> JP com_pcm_ch0)

### ISSUE THREAD

**Issue by hsk** [Stephane-D/SGDK#167]
I found bug on xgm driver when I read source code.
https://github.com/Stephane-D/SGDK/blob/master/src/z80_xgm.s80#L2068

This line is com_pcm_p1_ch1 -> JP com_pcm_ch0.
But I think com_pcm_p1_ch1 -> JP com_pcm_ch1.

**Comment by Stephane-D** [comment]
Oh nice catch ! Indeed a stupid copy/paste typo. Thanks for reveling it (i just fixed it) :)

**Comment by hsk** [comment]
Thank you very much. :)
