### ISSUE TITLE
Problème importation resources

### ISSUE THREAD

**Issue by izzidor** [Stephane-D/SGDK#171]
Bonjour,
 j'utilise SGDK avec Visual studio code, je rencontre un problème pour importé une resource "IMAGE".
J'ai créé un fichier .res dans le dossier " res " de mon projet, puis coller à l’intérieur ceci :  IMAGE   bgtile    "tbgtile.png"  0  
A la compilation j'ai l’erreur suivante  :
make : *** [res\resources.rs] error 127

Le fichier resources.h n'est pas généré.

Merci pour votre aide.

**Comment by izzidor** [comment]
Extrait du terminal : 
D:\ProgMD\teste>%GDK%\bin\make -f %GDK%\makefile.gen
d:/ProgMD/GenDev/bin/mkdir -p src/boot
d:/ProgMD/GenDev/bin/mkdir -p out
java -jar d:/ProgMD/GenDev/bin/rescomp.jar res/resources.res res/resources.rs -dep out/res/resources.o
d:/ProgMD/GenDev/bin/sh: java: command not found
make: *** [res/resources.rs] Error 127

**Comment by izzidor** [comment]
Probléme regler avec l'installation de l'extension " java extension pack "

**Comment by Stephane-D** [comment]
Désolé pour la réponse un peu tardive, mais oui SGDK nécessite Java (c'est indiqué dans le fichier readme) pour la compilation des ressources :)

**Comment by izzidor** [comment]
Pas de souci, et merci pour ton travail !
