### ISSUE TITLE
String formatting for FIX32 values is broken

### ISSUE THREAD

**Issue by goodspark** [Stephane-D/SGDK#175]
```c
KLog_F2("a ", FIX32(0.1), " b ", FIX32(0.2));
```

Output:
```
KDEBUG MESSAGE: a 0.99 b 0.19
```

Expected:
```
KDEBUG MESSAGE: a 0.1 b 0.19
```

So the value is `0.1`, but is being printed out as `0.99`. Fortunately, this only seems to be a string formatting problem, since this works correctly:
```c
KLog_U1("test ", FIX32(0.1) < FIX32(0.2));
```
```
KDEBUG MESSAGE: test 1
```

**Comment by Stephane-D** [comment]
Thanks for reporting ! I already saw the bug year ago and i though I already fixed but it looks like not !
I just pushed a fix for it (for good this time) :)
