### ISSUE TITLE
[Question] AdLib support/conversion?

### ISSUE THREAD

**Issue by lab313ru** [Stephane-D/SGDK#184]
Hi,

Is it possible to use AdLib data in SGDK? It's very popular format/sound-card in MS-DOS games.
Format is:
```
0x00: register (1 byte)
0x01: value (1 byte)
0x02: timeDelta (2 bytes)
```

**Comment by Stephane-D** [comment]
I don't see exactly what you mean by Adlib data.
Adlib was kind of sound standard back in time, it was based on YM3812 chip initially which is FM OPL2 technology. The Mega Drive FM sound chip is OPN tech based, it's close but still a different beast and not directly compatible with it so there is no way to support that format as it.
