### ISSUE TITLE
make fail :)

### ISSUE THREAD

**Issue by DenTroge** [Stephane-D/SGDK#194]
%GDK_WIN%\bin\make -f %GDK_WIN%\makelib.gen
make: *** No rule to make target `D:/apps/SGDK/src/z80_drv0.s', needed by `D:/apps/SGDK/src/z80_drv0.o'.  Stop.

**Comment by Stephane-D** [comment]
Be sure that you're up to date with GitHub repository.
Also try to do a clean before:
`%GDK_WIN%\bin\make -f %GDK_WIN%\makelib.gen clean`
then rebuild:
`%GDK_WIN%\bin\make -f %GDK_WIN%\makelib.gen`

z80drv0.s file should be there (you can see that you have it in the github repo).
