### ISSUE TITLE
Does xgmRomBuilder actually support multiple xgm to generate roms?

### ISSUE THREAD

**Issue by denjhang** [Stephane-D/SGDK#203]
The documentation just says that rom construction of vgm is supported.

**Comment by Stephane-D** [comment]
Please don't open issue to ask question. 
You can ask them on [SGDK discord](https://discord.gg/WmduASex) or on [SpritesMind forum](http://gendev.spritesmind.net/forum/).
Did you read the xgmROMBuilder.txt file ? it gives some basics instruction about how it works.
