### ISSUE TITLE
Question about tilesets/maps

### ISSUE THREAD

**Issue by pladaria** [Stephane-D/SGDK#205]
Hi,

First of all, thanks for releasing this SDK! I'm having lots of fun programming the genesis.

I'm trying learn by writing a very simple platformer. I'm using the high level API to create a map:
```
TILESET resTileMap1 "maps/map1.png" BEST DUPLICATE
MAP resMap1 "maps/map1.png" resTileMap1 BEST
```
I'm able to display the map and move around. To detect where the player is I use `MAP_getTile` this way I know if the tile is floor, wall, etc.

But I'm unable to know on beforehand how the tiles are going to be ordered in memory. My current workflow is to compile, then I use the emulator to show the VRAM tiles and then hardcode the tile indexes in my code (for example, floor tiles: 23 and 26, wall tiles: 34 and 18, etc). This doesn't feel right. It doesn't seem to load the tiles in order of appearance in the tileset png so I'm unable to see a better way.

What's the expected workflow? 

--

**Update:** It looks like tiles are loaded in order of appearance in tileset (at least it visually seems so, not sure if that's just a coincidence or the expected behavior).

**Comment by Stephane-D** [comment]
Exactly they are stored in order of appearance in the image (top-left to right-bottom).
What you can do is to use 1 or 2 tile rows at the top just to order your tiles as you want then in your game logic you ignore those 1 or 2 tile rows by adding +8 or +16 offset on the Y position.

**Comment by pladaria** [comment]
That was exactly my solution :)

Thanks again!
