### ISSUE TITLE
Mention marsdev in the readme?

### ISSUE THREAD

**Issue by dleslie** [Stephane-D/SGDK#206]
At the moment the Readme refers to gendev as a possible alternative for Linux users; however, the Marsdev project tracks the `master` branch of sgdk _and_ provides 32x support. Could it be mentioned, as well?

https://github.com/andwn/marsdev

**Comment by Stephane-D** [comment]
Of course ! Thanks for notifying about it as I wasn't sure about how well SGDK was supported in MarsDev.
I updated the Readme :)
