### ISSUE TITLE
MAP using flipped tiles when tileset is defined using DUPLICATE 

### ISSUE THREAD

**Issue by pladaria** [Stephane-D/SGDK#207]
I've defined a tileset/map as:
```sh
TILESET resTileMap "maps/map.png" BEST DUPLICATE
MAP resMap "maps/map.png" resTileMap BEST
```
If I look at VRAM, everythings seems correct, flipped tiles have different tile entries:

![image](https://user-images.githubusercontent.com/579417/114352294-0229d000-9b6c-11eb-9e5d-4c2d4bd18176.png)

For example, see the "ramp", going up and down. That's correct.

But the map seems to render using flipped tiles. When rendering a "ramp down", instead of using a "ramp down tile", it uses a flipped "ramp up tile".

**Comment by Stephane-D** [comment]
Thanks for reporting, i see why we have this issue ! I just pushed a fix to rescomp :)

**Comment by Stephane-D** [comment]
Yeah, lucky timing :p
