### ISSUE TITLE
SGDK Devs Hammopig

### ISSUE THREAD

**Issue by PlaymanBR** [Stephane-D/SGDK#228]
Hi, thanks for the reply.

We are players who dreamed of having arcade versions like SNK / KOF 9x , Marvel fighting and Capcom / Street Fighter Alpha games series for Sega Genesis.

Please, could you know the work of my brazilian fighting game development team for genesis?

I am responsible for the development of the audio area.

We are also developing tools that speed up sprite production and game physics.

Here's our youtube channel for you to check it out.

https://www.youtube.com/playlist?list=PLO-5vY5uaWRt8VUzMrCrAj_BeCtK3PDya

We would be very happy if you could leave us comments and mention our projects in your portfolio.

Thank you very much!!  YOU and the SGDK has opened up new avenues for sega genesis lovers. :))

**Comment by Stephane-D** [comment]
Is this a duplicate ?
