### ISSUE TITLE
How for Generate Manual in CHM format ??

### ISSUE THREAD

**Issue by esbvaGames** [Stephane-D/SGDK#235]
I once with SFML, I remember having generated a Manual in .CHM format, but I can't here, I don't know if something was missing ???,
Here is that process. min 3:40, but here I can't generate the manual.chm. 
(Or if it's done already, post the download link), Thanks !!!

https://youtu.be/FaBsmuvUjtk (min 3:40).-

**Comment by Stephane-D** [comment]
In my case i'm using an older Code::Blocks version and i don't have that doxygen GUI stuff. I can only set some defaults options for doxygen and none of them allow to generate the CHM file. You may need to update your Code::Blocks or maybe add a specific docygen generation plugin. I think you can also use the doxygen tool in command line to be able to generate the .chm file.
I'm closing the issue as this is not really a issue about SGDK but more a support question about Code::Blocks itself :)
