### ISSUE TITLE
Megapack Compress in Rescomp

### ISSUE THREAD

**Issue by saintienn** [Stephane-D/SGDK#240]
I found this graphic compressor for mega drive (https://github.com/lab313ru/megapack-megadrive), but I have no idea how to integrate it on Rescomp. I believe that is very interesting how an alternative for heavy compress of  tiles and maps.

**Comment by Stephane-D** [comment]
There is an example of using it with SGDK here :
https://github.com/lab313ru/megapack-megadrive/tree/main/sega_test
So basically just by taking the example you should be able to use it, still they do something weird as it seems to use a block of memory without properly allocating it. I will try to look at it if the compressor is freely usable / available but i'm not sure..

**Comment by saintienn** [comment]
Thank you so much!!
