### ISSUE TITLE
Define bool size as 8 bits instead of 16

### ISSUE THREAD

**Issue by Darky-Lucera** [Stephane-D/SGDK#245]
When a user tries to use SGDK with a C++ project `#define bool` becomes illegal. 

By default, m68k GCC defines bool with 8 bits size. If you match this size C++ users would use the library easily without recompiling it. Furthermore, 8 bits to store two values is enough for everyone, and also probably the code could be smaller.

**Comment by Stephane-D** [comment]
I initially set it to u16 as usually that is the fastest type to use but for boolean operation i think it shouldn't make a big difference, We rarely use bool for arithmetic so that should be fine.
Updated bool to u8 now :)
