### ISSUE TITLE
Highlight&Shadow not caring about the priority bit in transparent tiles

### ISSUE THREAD

**Issue by GerardGascon** [Stephane-D/SGDK#246]
When drawing an image with some tiles with the priority bits set to high, I notice that the ones that are fully transparent SGDK doesn't set them to high, only the ones that have a color index different to 0.

Here is the image that SGDK draws:
![image](https://user-images.githubusercontent.com/52170489/159530906-a1196afb-b624-4554-98f5-45ae4f83ced2.png)
And here is marked what should be set to high priority:
![image](https://user-images.githubusercontent.com/52170489/159530926-dd15c47a-faea-433f-a65c-fd11334d9f8d.png)

In case you want to take a look at a test rom:
[HighlightShadow.zip](https://github.com/Stephane-D/SGDK/files/8326298/HighlightShadow.zip)

Thank you

**Comment by Stephane-D** [comment]
I think this issue has already been fixed. Can you try to replace your bin/rescomp.jar file by the one from the git repository and check if it still happens ? Thanks.

**Comment by GerardGascon** [comment]
Still happens, I left the test project in the issue in case you want to take a look yourself

**Comment by Stephane-D** [comment]
Didn't saw your reply. I checked and fixed it for good this time ! Sorry for the long awaited time for that !
