### ISSUE TITLE
Illegal operand src/z80_drv1.s80 line 512 : LD      BC, HL          ; BC' point to read buffer

### ISSUE THREAD

**Issue by olatignies** [Stephane-D/SGDK#259]
This operation is clearly illegal based on the Z80 documentation : http://z80-heaven.wikidot.com/instructions-set:ld
I will try to fix it, but I need to know what it does ...so it could take times :)

**Comment by Stephane-D** [comment]
This is just a fictive instruction simulated by the assembler i'm using, internally it's encoded as :
LD B, H
LD C, L
:)
