### ISSUE TITLE
VDP_setPalette dont exists?

### ISSUE THREAD

**Issue by XDOneDude** [Stephane-D/SGDK#261]
i was just importing graphic resources to a game that im making and i get this
how to i get to use VDP_setPalette and VDP_setPaletteColor...   PS: I IMPORTED GENESIS.H
![faa](https://user-images.githubusercontent.com/106700244/185746094-d53ff0d9-68d4-471b-833e-0d895d49c0e9.png)

**Comment by XDOneDude** [comment]
NAH, IGNORE THIS, I FIXED IT

**Comment by Stephane-D** [comment]
The methods are deprecated, need to use PAL_setxxx methods now :)
