### ISSUE TITLE
bad apple not fonctional in "gens"emulator

### ISSUE THREAD

**Issue by greatAznur** [Stephane-D/SGDK#270]
hi    my "gens" emulator and I also use a" kega fusion" refuses to read the rom "bad apple" gens implies that it is too large so it cannot be a megadrive rom 
by manipulating it and removing images it works 
what emulator do you use to run the rom ?

**Comment by Stephane-D** [comment]
You need to use more recent emulators, BlastEm is a good emulator and does support larger ROMs (both Gens and Kega are limited to 6 MB rom size).

**Comment by greatAznur** [comment]
ok thanks
