### ISSUE TITLE
Still failing to build with Genesis Code

### ISSUE THREAD

**Issue by Zapeltal** [Stephane-D/SGDK#277]
Hey,
I recently created an issue about failing to build with Genesis Code, and i figured out why it was'nt working.
I replaced the errors, and... it didn't work
![image](https://user-images.githubusercontent.com/105296830/200132175-fc508ded-648f-442c-872c-e66f3d74259f.png)

**Comment by LIZARDRIVE** [comment]
When switching to a new SGDK version, you may need to clean your project folder in order to compile properly.
Get rid of "out" folder (which includes generated .o files) and try again.
If it's still not working delete eveyrthing but what you created yourself.
