### ISSUE TITLE
VDP_loadFont() omits duplicate chars

### ISSUE THREAD

**Issue by moon-watcher** [Stephane-D/SGDK#278]
My custom font use the same char for 0 and O and here is the result:
![imagen](https://user-images.githubusercontent.com/786274/202929627-f4951d52-b705-4419-9cba-8db271641ca7.png)

It doesn't load the O since 0 is already loaded

**Comment by Stephane-D** [comment]
Did you disabled optimisation when defining the font resource (probably as TILESET) ? otherwise rescomp will remove any duplicate tiles in the tileset.

**Comment by moon-watcher** [comment]
My fault. Had this line on res file
`TILESET font01 "gfx/font/font.png" NONE`

Since it's a font I assumed erroneous things and missed 4th parameter for optimization.

May be ok to add a new resource FONT just like TILESET but without tile optimization
