### ISSUE TITLE
rescomp: same tileset for multiple maps

### ISSUE THREAD

**Issue by thegabman** [Stephane-D/SGDK#279]
Hi,
I am trying to have one tileset for multiple maps. So I have a PNG consisting of all unique tiles and 2 map PNGs composed of a subset of exactly these unique tiles. 

In my resource file I defined a TILESET with my tileset.png and try to define 2 times a MAP with map1.png and map2.png. Both get the previously defined tileset as an input. 

My problem now is, that rescomp complains that tile [0,0] cannot be found while compiling map1.png. 

If I create my TILESET using the map1.png it works fine. But that way I cannot share the tileset between different maps if there is no map with all unique tiles used at least once. 

Is there something special to consider?
Thank you 🙏

**Comment by Stephane-D** [comment]
Issue closed (tileset and map had different palette).
