### ISSUE TITLE
topic addition for better community reach

### ISSUE THREAD

**Issue by Wladefant** [Stephane-D/SGDK#283]
Hey,
for better reach of the community, I would like to suggest to add the following topic to the repository: `motorola-68000`

[How to do this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository)

**Comment by Stephane-D** [comment]
Just added, thanks for the suggestion :)
