### ISSUE TITLE
Fail to build on windows

### ISSUE THREAD

**Issue by skarab** [Stephane-D/SGDK#284]
Hello, I just got the latest version and when I build I get this :

src/boot/sega.s:256: Error: invalid operands (*UND* and *UND* sections) for `+'

**Comment by skarab** [comment]
Ok my makefile is outdated, sorry

**Comment by Stephane-D** [comment]
Yeah It was, I recently added some options in build command to accept these caracters :)

**Comment by skarab** [comment]
Yes, gonna upgrade to latest rev, it's a huge step up ! (was using version just before the whole sprite system rewrite :)

**Comment by Strugglemeat** [comment]
I'm having the same issue, where can I get a new makefile?

**Comment by Stephane-D** [comment]
Just directly download the last SGDK github archive, that should work :)

**Comment by skarab** [comment]
New makefile is in SGDK/makefile.gen (I had copied it to personnalize in old version, my trouble was I forget to update it)
