### ISSUE TITLE
SpriteEngine - auto anim

### ISSUE THREAD

**Issue by skarab** [Stephane-D/SGDK#296]
Hi! By now it's not possible to bypass the auto frames animation, it looks its reset in the visibility update, I have hard patched it in the lib but it would be cool to have an option to wholy disable sprite->timer things.
Cheers!

**Comment by Stephane-D** [comment]
Not sure to understand this one, normally setting sprite->timer to 0 is enough to disable auto animation.

**Comment by skarab** [comment]
Great thanks.

**Comment by skarab** [comment]
Just a side note, to get it working we need to set sprite->timer to 0 at each frame, else it got overwriden by static u16 updateFrame(Sprite* sprite, u16 status)

**Comment by Stephane-D** [comment]
Indeed, it requires to reset timer to 0 each time you change frame.
I added a new SPR_setAutoAnimation(sprite, bool) method to take care of that in a better way :)
