### ISSUE TITLE
ResComp Crash

### ISSUE THREAD

**Issue by darkstack** [Stephane-D/SGDK#30]
When i was compiling a PNG file (with an invalid palette between 2 tiles) as a SPRITE ResComp keep crashing, after a quick look up here's what i found:

Sprite.c in the Execute function : 

    sprDef = getSpriteDefinition(data, wt, ht, wf, hf, time, collid);  (return null due to invalid palette in getTile)

    removeEmptyFrame(sprDef);

if sprDef is null  removeEmptyFrame access member of sprDef crashing ResComp.

**Comment by Stephane-D** [comment]
Thanks for the report, just committed the fix !
