### ISSUE TITLE
issues in Docker

### ISSUE THREAD

**Issue by loki666** [Stephane-D/SGDK#304]
https://github.com/Stephane-D/SGDK/blob/2a24303a628913808b95872abaa691eecd9dd27b/bin/create-bin-wrappers.sh#L14C11-L14C11

this creates a loop of shells
mkdir (shell script) calls mkdir but since /sgdk is first in the PATH, it calls again the mkdir shell script

use "/bin/mkdir" in the wrapper

**Comment by joeyparrish** [comment]
PR #316 would remove create-bin-wrappers and build a universal Docker image with native Linux executables inside.
