### ISSUE TITLE
GDK not working properly despite following the installation step by step.

### ISSUE THREAD

**Issue by AdonisStickmanGITHUB** [Stephane-D/SGDK#318]
PS C:\SGDK> %GDK%\bin\make -f %GDK%\makefile.gen clean
%GDK%\bin\make : The module '%GDK%' could not be loaded. For more information, run 'Import-Module %GDK%'.
At line:1 char:1
+ %GDK%\bin\make -f %GDK%\makefile.gen clean
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (%GDK%\bin\make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

PS C:\SGDK> Import-Module %GDK%
Import-Module : The specified module '%GDK%' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module %GDK%
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (%GDK%:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by Stephane-D** [comment]
SGDK is meant to be used from 'cmd' command line tool, not powershell.
