### ISSUE TITLE
Feature request:  abs()

### ISSUE THREAD

**Issue by nolddor** [Stephane-D/SGDK#32]
Just implement abs() function in math.h /math.c

**Comment by Stephane-D** [comment]
Actually this is done in my WIP version, just not yet committed ;)

**Comment by nolddor** [comment]
Hehehe I wasnt sure if you remember about I told you in twitter.
So,... i thought this was the better way to submit a issue officially ;)

Thanks for your good work as always :D

**Comment by Stephane-D** [comment]
Actually it was not fast to do that i did it immediately, thanks for opening an issue anyway, as indeed tht is the best way for me to not forget usually :)
