### ISSUE TITLE
XGM2 tempo off on PAL

### ISSUE THREAD

**Issue by matteusbeus** [Stephane-D/SGDK#340]
Unlike the original XGM I'm having to set the XGM2_setMusicTempo to 60 to get things to play at the correct speed? Is this by design or is the detection not working properly?

**Comment by Stephane-D** [comment]
To be honest I'm not sure why it doesn't work, default is 60 tick / second and it should work for both PAL or NTSC. Maybe the value was reset for some reason. Anyway I push a fix which was needed to properly adjust timing depending the PAL / NTSC track info.
