### ISSUE TITLE
Error in rescomp a collision type is specified

### ISSUE THREAD

**Issue by moon-watcher** [Stephane-D/SGDK#35]
![error_img_1](https://cloud.githubusercontent.com/assets/786274/10713705/42716254-7ac5-11e5-9b41-dc9acb14c0b9.png)
![error_img_2](https://cloud.githubusercontent.com/assets/786274/10713706/428d8be6-7ac5-11e5-9f8c-d7d8be1f4a4f.png)

In Rescomp, a duplicate label is generated using the SPRITE resource when the collision type is set to BOX or CIRCLE. Works if NONE or empty.

**Comment by Tamk1s** [comment]
I mentioned this same problem earlier in a Spritesmind post (http://gendev.spritesmind.net/forum/viewtopic.php?f=19&t=2034#top), but good that you actually logged this as an issue

**Comment by Stephane-D** [comment]
Thanks for the report, will be fixed in next version !
