### ISSUE TITLE
No libres.h

### ISSUE THREAD

**Issue by bilibiliLaiabao55** [Stephane-D/SGDK#353]
when i use sgdk in vscode
one of those `.h` file try to include a file named `libres.h`
but i check the `inc` folder
there is no `libres.h`
can i just delete this code?

<img width="313" alt="屏幕截图 2024-09-19 115229" src="https://github.com/user-attachments/assets/ab757107-03b5-484b-9fea-9ab09f051645">

**Comment by Stephane-D** [comment]
This is not the good place to ask for support. 
The libres.h file is automatically generated when you build the library and normally it should be already included in the `res` folder (the file is the header of the library resources).

**Comment by bilibiliLaiabao55** [comment]
thanks
