### ISSUE TITLE
Split 	SPR_setAttribut() / 	SPR_setPosition() into more specific functions

### ISSUE THREAD

**Issue by nolddor** [Stephane-D/SGDK#36]
Because you sometimes only want to change HFLIP, VFLIP,.... should be interesting create an especific funcion for each task, in addition to SPR_setAttribut()

An example could be: 

void SPR_setHFlip( Sprite *sprite, u8 HFlip )
{
	if( HFlip )
	{
		sprite->attribut |= ( 1<<11 );
	}
	else
	{
		sprite->attribut &= ~( 1<<11 );
	}
}

Others interesting functions:
SPR_setVFlip
SPR_setPalette
SPR_setPriority

The same with SPR_setPosition... 
SPR_setPositionX
SPR_setPositionY
Should be created in order to update only one axis.

**Comment by Stephane-D** [comment]
I think the attributes methods are interesting but decoupling position doesn't have much interest (you rarely update only one of them).

**Comment by nolddor** [comment]
It's depend on the game, in my two last games I've never update both axis at the same time... but yes I more important attributes methods than position

**Comment by Stephane-D** [comment]
Hehe, you are probably developing specifics games then :p The thing is that i don't like having too much methods... I did at least the attributes methods, i will think about position... anyway i have to rework a bit this Sprite Engine stuff ;)
