### ISSUE TITLE
How can I build mmd files?

### ISSUE THREAD

**Issue by bilibiliLaiabao55** [Stephane-D/SGDK#375]
Like the title
I want to build mmd file for my sega cd game
But I don't know how to do it
Please help me.
repositories link: `https://github.com/bilibiliLaiabao55/MEGARUNE`

**Comment by Stephane-D** [comment]
This is not a place to ask support for, better to join the SGDK Discord server for that : https://discord.gg/xxgF6ebB
Also SGDK does not support Sega CD, only Sega Mega Drive.

**Comment by bilibiliLaiabao55** [comment]
thanks
