### ISSUE TITLE
SPR_getAnimationDone() is missing

### ISSUE THREAD

**Issue by moon-watcher** [Stephane-D/SGDK#382]
https://github.com/Stephane-D/SGDK/blob/617e3cb5118be3b1e5c30ef0b778bd675e1e9485/inc/sprite_eng.h#L49

According to the changelog SPR_getAnimationDone() was added in SGDK 1.90 but unnincluded in source code

**Comment by moon-watcher** [comment]
Use SPR_isAnimationDone()

**Comment by Stephane-D** [comment]
Method has simply be renamed :)
