### ISSUE TITLE
RGB24_TO_VDPCOLOR is BGR

### ISSUE THREAD

**Issue by clbr** [Stephane-D/SGDK#40]
The RGB24_TO_VDPCOLOR macro is BGR, nor RGB.

VDP_setPaletteColor(63, RGB24_TO_VDPCOLOR(0xff0000));

sets the color to blue, even though it should be red.

**Comment by Stephane-D** [comment]
I remember someone given me that macro, i never used it myself, that explain partially why it's still wrong :p
