### ISSUE TITLE
recomp sprite collision

### ISSUE THREAD

**Issue by Ced2911** [Stephane-D/SGDK#48]
Hi, rescomp readme is wrong:
Collision should be set to box by default:
https://github.com/Stephane-D/SGDK/blob/master/tools/rescomp/rescomp.txt#L143
but:
https://github.com/Stephane-D/SGDK/blob/10f2039eacac7d72a6eb63b274af6b95c91a85b8/tools/rescomp/src/sprite.c#L72
it's set to none

**Comment by Stephane-D** [comment]
Thanks for the report ! I fixed the documentation (still in my WIP so we be available in next version) !
