### ISSUE TITLE
recomp sprite collision, wrong label name

### ISSUE THREAD

**Issue by Ced2911** [Stephane-D/SGDK#49]
Labels name are generated multiple time:
see 
https://gist.github.com/Ced2911/78f848ebb4bb1dba6a47#file-gfx-s-L1247
https://gist.github.com/Ced2911/78f848ebb4bb1dba6a47#file-gfx-s-L1259
using this .res file:
https://gist.github.com/Ced2911/78f848ebb4bb1dba6a47#file-gfx-res

**Comment by Stephane-D** [comment]
This one has been fixed in my WIP version. I cannot make it available though as i have others big changes in the work :-/ consider than currently collision fields are not yet supported but they will in next version !
