### ISSUE TITLE
Move QtCreator info to local GitHub wiki

### ISSUE THREAD

**Issue by AbigailBuccaneer** [Stephane-D/SGDK#54]
Hi. A while back (before SGDK moved from Google Code to GitHub) I wrote the instructions for using QtCreator with SGDK, and put them in the wiki of my own GitHub exported version of SGDK.

Now SGDK's officially on GitHub, but the QtCreator pages are still on my wiki. I don't have any plans to maintain them so it makes no sense for them to be on my version of the SGDK repository (which I was about to delete, before I remembered the QtCreator docs).

I've just updated my version's wiki's `master` branch to be ahead of yours and merge in the QtCreator info.

Please merge `https://github.com/AbigailBuccaneer/sgdk.wiki.git` into `https://github.com/Stephane-D/SGDK.wiki.git`. It should be a simple fast-forward merge.

**Comment by Stephane-D** [comment]
Thanks for letting me know that, i merged the wiki, should be fine now :)
