### ISSUE TITLE
Sprite "rolls" from posx 384 back to 184, but from posy 1016 back to 0.

### ISSUE THREAD

**Issue by s7jones** [Stephane-D/SGDK#58]
I'm trying to make a simple "Snake" game, where I control a sprite which is represented by a block.

If I'm going horizontally right- then I increment the sprite.posx by + 8. It will reach 384 (sometimes only 376 if I frame step slowly) but the next position is 128.

It does not do this vertically, instead when doing sprite.posy + 8, it will reach 1016 and reset to 0.

Is the sprite area not defined to be 512x512 starting at 128,128?

I've got these values using GensKmod, but I get the same behaviour in Fusion.

My code looks like this:
```

	while(1)
	{

	if (count > 5) {
		switch (steer) { // I change steer elsewhere
		case up:
			snakeSprite->posy = snakeSprite->posy - 8;
			direction = up;
			break;
		case down:
			snakeSprite->posy = snakeSprite->posy + 8;
			direction = down;
			break;
		case left:
			snakeSprite->posx = snakeSprite->posx - 8;
			direction = left;
			break;
		case right:
			snakeSprite->posx = snakeSprite->posx + 8;
			direction = right;
			break;
		}
		count = 0;
	}
	else count++;

		VDP_setSpriteP(0, &snakeSprite);
		VDP_updateSprites();

		VDP_waitVSync();

	}

```

Any advice you could give would be appreciated.

**Comment by Stephane-D** [comment]
You need to understand how sprites are internally handle by Megadrive hardware :
http://md.squee.co/VDP#Sprite_Attribute_Table

As you can see, 10 bits are used for vertical position while only 9 bits are used for horizontal position. so what you see is expected.
