### ISSUE TITLE
Rescomp: drawing a compressed image shows trash 

### ISSUE THREAD

**Issue by moon-watcher** [Stephane-D/SGDK#62]
Got this line in a .res file 
`IMAGE screen_gameover_all "../../data/all/screens/gameover.bmp" -1`

Calling VDP_drawImageEx() shows trash only it the compressed param is set to -1 (or 1). The strangest thing about this case is that it only happends with this image https://app.box.com/s/cy0s3gtm01sh0vin0mlw428f8niz0z2d

**Comment by moon-watcher** [comment]
If I resize it for example to 144x32 it works

**Comment by Stephane-D** [comment]
Hey ! Just wanted to know if you still experience the issue ? I think i fixed it with the last SGDK but i want to be sure before closing it (i can't download the image from your link).

**Comment by Stephane-D** [comment]
I assume this one to be fixed :)
