### ISSUE TITLE
undefined reference to 'currenZ80Driver'

### ISSUE THREAD

**Issue by guerrerotook** [Stephane-D/SGDK#63]
Hi,

I´m having some issues bulding the code, here is the log coming from Eclipse:

```
19:57:30 **** Incremental Build of configuration release for project testing ****
"C:\\SGDK\\bin\\make" -f C:/SGDK/makefile.gen release 
C:/SGDK/bin/gcc -BC:/SGDK/bin -n -T C:/SGDK/md.ld -nostdlib out/sega.o @out/cmd_ C:/SGDK/lib/libmd.a C:/SGDK/lib/libgcc.a -o out/rom.out
C:/SGDK/lib/libmd.a(sys.o): In function `_vint_callback':
**sys.c:(.text+0x726): undefined reference to `currentZ80Driver'**
make: *** [out/rom.out] Error 1
```

**Comment by Stephane-D** [comment]
Hi,

Apparently i made a mistake in the archive but it's fixed in the WIP. If you download the sources files from repository it should fix the issue (actually the sys.c file contains reference to currentZ80Driver which has been renamed currentDriver lately).
