### ISSUE TITLE
Feature request: VDP_updateSpritesDMAQ

### ISSUE THREAD

**Issue by clbr** [Stephane-D/SGDK#67]
VDP_updateSprites does the update immediately at that point. I think an alternative, VDP_updateSpritesDMAQ, that created a temp memory array and pushed the update to the DMA queue would be useful.

This would defer the actual update to the next vblank, and in an easy way usable by many programs. Manually setting up that would be quite a bit more involved.

**Comment by Stephane-D** [comment]
In fact i already have it done in the WIP version ;) 
I really need to push my changes even if everything is not yet done as i received many requests / fixes  already implemented lately  :D
I plan to implement DMA queue for all methods using DMA in future.
