### ISSUE TITLE
Illegal instruction! when testing rom

### ISSUE THREAD

**Issue by salvadorc17** [Stephane-D/SGDK#75]
Hi, i have managed to compile a rom using CodeBlocks, and following tutorial, but when want to test rom in any emulator got "Illegal instruction" message

**Comment by Stephane-D** [comment]
Hi Salvador,
I guess there is something really wrong with your code then :-/ What is your code ?

**Comment by salvadorc17** [comment]
Not really, is the hello world tutorial code, how can be wrong

**Comment by Stephane-D** [comment]
Oh indeed there is something really wrong with the development environment then...
Is it possible that several GCC compilers are conflicting together so you end up with the wrong GCC being used to compile the rom ? The test rom you are using is rom.bin file ?

**Comment by salvadorc17** [comment]
Yes, it is, also i dont have multiple GCC compiler only this one used for SGDK, unless is problem with Code Blocks?

**Comment by Stephane-D** [comment]
Can you try a build rebuild (using rebuild or clean/build) and send the compilation log ?

**Comment by salvadorc17** [comment]
Ok, thanks i found the problem was missing the while statement.

**Comment by Stephane-D** [comment]
Oh ok, indeed you need it otherwise program end by executing outside of range code...
I can close the issue now :)
