### ISSUE TITLE
There is no differences between libmd release and debug one

### ISSUE THREAD

**Issue by lab313ru** [Stephane-D/SGDK#81]
Subj.
So size/etc. optimization doesn't work at all!

**Comment by Stephane-D** [comment]
What do you mean exactly by "no difference" ? At least the library size is not the same. Also now debug target use optimization level 1 (while release use O3) so performance even in debug are already good.

**Comment by lab313ru** [comment]
I mean, that after compilation on Windows, libmd.a, and libmd_debug.a have the same sizes.
And my tries to change compilation flags don't change that difference.

**Comment by lab313ru** [comment]
This is a compilation log.
[build_lib.zip](https://github.com/Stephane-D/SGDK/files/1090894/build_lib.zip)

**Comment by Stephane-D** [comment]
Oh yeah you need to do a clean between release / debug. Maybe something to change in the makefile to avoid that...

**Comment by Stephane-D** [comment]
I fixed the build script ;)
