### ISSUE TITLE
maths3D_a.s misprint

### ISSUE THREAD

**Issue by lab313ru** [Stephane-D/SGDK#82]
This line references wrong label: https://github.com/Stephane-D/SGDK/blob/master/src/maths3D_a.s#L83
It should reference to here: https://github.com/Stephane-D/SGDK/blob/master/src/maths3D_a.s#L135

**Comment by Stephane-D** [comment]
It doesn't make real difference, does it ?

**Comment by lab313ru** [comment]
It makes. Because this label is not visible by good assemblers. And it will be correct to point to near label.

**Comment by Stephane-D** [comment]
Ok, i fixed it :) thanks !
