### ISSUE TITLE
Section name specifying or just a label?

### ISSUE THREAD

**Issue by lab313ru** [Stephane-D/SGDK#84]
https://github.com/Stephane-D/SGDK/blob/master/src/smp_null.s

I mean ".text" at the first line.

**Comment by lab313ru** [comment]
And why this alignment is so big?

**Comment by Stephane-D** [comment]
Section name, is it wrong declared as it ? and 256 bytes alignment is required by the sound driver :)

**Comment by lab313ru** [comment]
If it is section name, it should not be declared as a label, starting a new line, because every directive should be started with indent. Or not?

**Comment by Stephane-D** [comment]
I think it work in both case but to be safe, i fixed it with :)
