### ISSUE TITLE
abs and fix32

### ISSUE THREAD

**Issue by Kivutar** [Stephane-D/SGDK#86]
I'm not sure if it affects master, I was only able to test it in gendev which is using an old version of SGDK.

This code is not working when dx and dy are fix32:

    if abs(dy) <= abs(dx)

I had to workaround like this:

    fix32 adx = abs(dx);
    fix32 ady = abs(dy);
    if (ady < adx)

**Comment by Stephane-D** [comment]
Yep, that issue is fixed in the last version ;) Thanks for reporting anyway, good to double check ;)
