### ISSUE TITLE
hello world example results in illegal instruction crash

### ISSUE THREAD

**Issue by longjoel** [Stephane-D/SGDK#89]
![image](https://user-images.githubusercontent.com/1072320/28491100-dbb24282-6eaf-11e7-96fb-17a910cc6211.png)

happens with both picodrive and dgen.

**Comment by Stephane-D** [comment]
To be honest i sincerely doubt there is something wrong with the hello word sample :p
The issue is probably somewhere in the dev environment setup or in your emulator.
How did you compile your rom ?
