### ISSUE TITLE
Make debug working extremely strange...

### ISSUE THREAD

**Issue by minerscale** [Stephane-D/SGDK#91]
I don't know what the problem is but by game builds and runs as expected when I make normally but if I make debug parts of my tiles are not there... Not sure what the problem is, I'm using gendev, if it makes a difference.
[rom.zip](https://github.com/Stephane-D/SGDK/files/1202811/rom.zip)

![ahh](https://user-images.githubusercontent.com/20499616/29000011-fc23550e-7aa0-11e7-8d30-911469c65119.png) - made with release
![oh](https://user-images.githubusercontent.com/20499616/29000012-fda0d4c4-7aa0-11e7-87d0-85d270a0fbde.png) - made with debug

EDIT: Oops! Sorry got the release and debug tags wrong...

**Comment by Stephane-D** [comment]
Is it fixed or not ?

**Comment by minerscale** [comment]
No, it's not fixed... I just labelled  the images wrong... :p

**Comment by Stephane-D** [comment]
The thing is that without your project source code i'm not able to reproduce this problem... i never observed it and i'm using *a lot* the debug target so i really need your project folder to understand what is going wrong there :)

**Comment by minerscale** [comment]
Oh... ok then. I was keeping it closed source for the moment. But, whatever. It's so early in development that it doesn't matter. I was in the middle of testing the level system so when you press start it changes level \o/

**Comment by Stephane-D** [comment]
If you feel more comfortable with you can just distribute a minimal example which can reproduce the issue but i think that is the whole which make the problem to appears ;)

**Comment by minerscale** [comment]
No, it's fine. I'll just send it over :)

On 11 August 2017 at 22:58, Stephane Dallongeville <notifications@github.com

**Comment by Stephane-D** [comment]
Ok thanks i will try to reproduce the issue here then :)

**Comment by minerscale** [comment]
cool :)

Do you have any insight of what's going on?

On 11 August 2017 at 23:04, Stephane Dallongeville <notifications@github.com

**Comment by Stephane-D** [comment]
Absolutely no idea for now to be honest... debug and release should produce the same result, the only difference is about speed but i don't see how it can generate different "visible" results..

**Comment by minerscale** [comment]
huh, alright then. Hope you find something.

On 11 August 2017 at 23:09, Stephane Dallongeville <notifications@github.com

**Comment by Stephane-D** [comment]
Do you observe the bug only on real hardware ? Testing quickly with Fusion i can't see any differences with debug and release builds. Also i have only 2 levels, first have yellow block while second has some weird characters blocks, is it expected ?

**Comment by minerscale** [comment]
Yeah, the weird character blocks are expected (Test sprites lol). Believe it or not, I don't actually have a Mega Drive to test with yet... (yet). It's working fine for me too... Must be quite selective... This is a different build of the game to what the original bug report, however there might be a build in the git repo that the bug is reproducible in. Yeah there is, just checked... Here's the reproducible build. Crazy how much it's changed in just 6 days! The already built rom is the erroneous rom built with debug.
[genesis-rpg.zip](https://github.com/Stephane-D/SGDK/files/1219719/genesis-rpg.zip)

**Comment by Stephane-D** [comment]
Ok, i had a quick look on your sources ans realized you don't protect VDP access with SYS_disableInts() / SYS_enableInts() couple. It's important to protect any VDP accesses (as VDP_setTilemapXY(..)) otherwise you can screw up the VDP state because SGDK V-Interrupt callback will access VDP too.
Adding the SYS_disableInts() / SYS_enableInts() where you need it fix the issue.

**Comment by minerscale** [comment]
Huh, ok then. Good to know. I'll add that now. Might be a good idea to put that somewhere in the wiki :p
