### ISSUE TITLE
Image struct seems broken

### ISSUE THREAD

**Issue by arturleao** [Stephane-D/SGDK#93]
Can't get to load a simple image background using Image struct and VDP_loadBMPTileData/VDP_fillTileMapRectInc.

Works fine when we feed it a Bitmap instead.

**Comment by Stephane-D** [comment]
You need to use the VDP_drawImage(..) or VDP_drawImageEx(..) methods.
Image and Bitmap has different memory organization, IMAGE is the one which fit VDP internals structures while BITMAP is just to use with the SGDK bitmap engine.
